/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_memory_projectMemory_add_parameter_0$schema = z.object({
  'content': z.string().readonly(),
  'ifRevision': z.number().readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const dsh_memory_projectMemory_add_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceTitle': z.string().readonly(),
  'revision': z.number().readonly(),
  'maxEntries': z.number().readonly(),
  'maxEntryChars': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'content': z.string().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'origin': z.union([z.literal("tool"), z.literal("command"), z.literal("ui")]).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-unavailable").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'current': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceTitle': z.string().readonly(),
  'revision': z.number().readonly(),
  'maxEntries': z.number().readonly(),
  'maxEntryChars': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'content': z.string().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'origin': z.union([z.literal("tool"), z.literal("command"), z.literal("ui")]).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("content-blank").readonly(),
}), z.object({
  'code': z.literal("content-nul").readonly(),
}), z.object({
  'code': z.literal("content-too-long").readonly(),
  'maxChars': z.number().readonly(),
  'actualChars': z.number().readonly(),
}), z.object({
  'code': z.literal("capacity-reached").readonly(),
  'maxEntries': z.number().readonly(),
}), z.object({
  'code': z.literal("memory-not-found").readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])
const dsh_memory_projectMemory_delete_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'ifRevision': z.number().readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const dsh_memory_projectMemory_delete_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceTitle': z.string().readonly(),
  'revision': z.number().readonly(),
  'maxEntries': z.number().readonly(),
  'maxEntryChars': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'content': z.string().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'origin': z.union([z.literal("tool"), z.literal("command"), z.literal("ui")]).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-unavailable").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'current': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceTitle': z.string().readonly(),
  'revision': z.number().readonly(),
  'maxEntries': z.number().readonly(),
  'maxEntryChars': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'content': z.string().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'origin': z.union([z.literal("tool"), z.literal("command"), z.literal("ui")]).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("content-blank").readonly(),
}), z.object({
  'code': z.literal("content-nul").readonly(),
}), z.object({
  'code': z.literal("content-too-long").readonly(),
  'maxChars': z.number().readonly(),
  'actualChars': z.number().readonly(),
}), z.object({
  'code': z.literal("capacity-reached").readonly(),
  'maxEntries': z.number().readonly(),
}), z.object({
  'code': z.literal("memory-not-found").readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])
const dsh_memory_projectMemory_list_parameter_0$schema = z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const dsh_memory_projectMemory_list_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceTitle': z.string().readonly(),
  'revision': z.number().readonly(),
  'maxEntries': z.number().readonly(),
  'maxEntryChars': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'content': z.string().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'origin': z.union([z.literal("tool"), z.literal("command"), z.literal("ui")]).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.object({
  'code': z.literal("workspace-unavailable").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}).readonly(),
})])
const dsh_memory_projectMemory_update_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'content': z.string().readonly(),
  'ifRevision': z.number().readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
})
const dsh_memory_projectMemory_update_result$schema = z.union([z.object({
  'ok': z.literal(true).readonly(),
  'value': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceTitle': z.string().readonly(),
  'revision': z.number().readonly(),
  'maxEntries': z.number().readonly(),
  'maxEntryChars': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'content': z.string().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'origin': z.union([z.literal("tool"), z.literal("command"), z.literal("ui")]).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'ok': z.literal(false).readonly(),
  'error': z.union([z.object({
  'code': z.literal("workspace-unavailable").readonly(),
  'sessionId': z.intersection(z.string(), z.unknown()).readonly(),
}), z.object({
  'code': z.literal("revision-conflict").readonly(),
  'current': z.object({
  'workspaceId': z.intersection(z.string(), z.unknown()).readonly(),
  'workspaceTitle': z.string().readonly(),
  'revision': z.number().readonly(),
  'maxEntries': z.number().readonly(),
  'maxEntryChars': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'content': z.string().readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
  'origin': z.union([z.literal("tool"), z.literal("command"), z.literal("ui")]).readonly(),
})).readonly(),
}).readonly(),
}), z.object({
  'code': z.literal("content-blank").readonly(),
}), z.object({
  'code': z.literal("content-nul").readonly(),
}), z.object({
  'code': z.literal("content-too-long").readonly(),
  'maxChars': z.number().readonly(),
  'actualChars': z.number().readonly(),
}), z.object({
  'code': z.literal("capacity-reached").readonly(),
  'maxEntries': z.number().readonly(),
}), z.object({
  'code': z.literal("memory-not-found").readonly(),
  'id': z.intersection(z.string(), z.unknown()).readonly(),
})]).readonly(),
})])

export const TYPERT = {
  package: 'dsh-memory',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-memory#projectMemory/add',
      service: 'projectMemory',
      namespace: 'projectMemory',
      method: 'add',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-memory/types#ProjectMemoryAddRequest',
            schema: dsh_memory_projectMemory_add_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-memory/types#ProjectMemoryResult',
        schema: dsh_memory_projectMemory_add_result$schema,
      },
      sourceLocation: {"file":"packages/memory/dsh-memory/src/index.ts","line":355,"column":3},
    },
    {
      id: 'dsh-memory#projectMemory/delete',
      service: 'projectMemory',
      namespace: 'projectMemory',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-memory/types#ProjectMemoryDeleteRequest',
            schema: dsh_memory_projectMemory_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-memory/types#ProjectMemoryResult',
        schema: dsh_memory_projectMemory_delete_result$schema,
      },
      sourceLocation: {"file":"packages/memory/dsh-memory/src/index.ts","line":379,"column":3},
    },
    {
      id: 'dsh-memory#projectMemory/list',
      service: 'projectMemory',
      namespace: 'projectMemory',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-memory/types#ProjectMemoryListRequest',
            schema: dsh_memory_projectMemory_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-memory/types#ProjectMemoryResult',
        schema: dsh_memory_projectMemory_list_result$schema,
      },
      sourceLocation: {"file":"packages/memory/dsh-memory/src/index.ts","line":342,"column":3},
    },
    {
      id: 'dsh-memory#projectMemory/update',
      service: 'projectMemory',
      namespace: 'projectMemory',
      method: 'update',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-memory/types#ProjectMemoryUpdateRequest',
            schema: dsh_memory_projectMemory_update_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-memory/types#ProjectMemoryResult',
        schema: dsh_memory_projectMemory_update_result$schema,
      },
      sourceLocation: {"file":"packages/memory/dsh-memory/src/index.ts","line":367,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Storage owner and all first-party Project Memory entry points.",
        "summary": "Storage owner and all first-party Project Memory entry points.",
        "tags": [],
        "jsDoc": "/** Storage owner and all first-party Project Memory entry points. */",
        "key": "projectMemory",
        "exportName": "ProjectMemoryService",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote('list') list(request: ProjectMemoryListRequest): Promise<ProjectMemoryResult<ProjectMemoryWorkspaceUnavailable>>",
            "summary": "Read the current snapshot resolved from a Session's workspace membership.",
            "jsDoc": "/**\n * Read the current snapshot resolved from a Session's workspace membership.\n * @param request - Session whose attached workspace is addressed.\n * @returns the immutable current snapshot or `workspace-unavailable`.\n */"
          },
          {
            "kind": "method",
            "name": "add",
            "signature": "@Remote('add') add(request: ProjectMemoryAddRequest): Promise<ProjectMemoryResult>",
            "summary": "Add one newest-first entry through the Web Remote.",
            "jsDoc": "/**\n * Add one newest-first entry through the Web Remote.\n * @param request - content and observed workspace revision.\n * @returns the committed snapshot or an explicit business failure.\n */"
          },
          {
            "kind": "method",
            "name": "update",
            "signature": "@Remote('update') update(request: ProjectMemoryUpdateRequest): Promise<ProjectMemoryResult>",
            "summary": "Replace one entry through the Web Remote without changing list order.",
            "jsDoc": "/**\n * Replace one entry through the Web Remote without changing list order.\n * @param request - entry id, replacement content, and observed revision.\n * @returns the committed snapshot or an explicit business failure.\n */"
          },
          {
            "kind": "method",
            "name": "delete",
            "signature": "@Remote('delete') delete(request: ProjectMemoryDeleteRequest): Promise<ProjectMemoryResult>",
            "summary": "Delete one entry through the Web Remote.",
            "jsDoc": "/**\n * Delete one entry through the Web Remote.\n * @param request - entry id and observed revision.\n * @returns the committed snapshot or an explicit business failure.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "ProjectMemoryAddRequest",
            "declaration": "export interface ProjectMemoryAddRequest extends ProjectMemoryListRequest {\n    readonly content: string;\n    readonly ifRevision: number;\n}"
          },
          {
            "name": "ProjectMemoryCapacityReached",
            "declaration": "export interface ProjectMemoryCapacityReached {\n    readonly code: 'capacity-reached';\n    readonly maxEntries: number;\n}"
          },
          {
            "name": "ProjectMemoryContentBlank",
            "declaration": "export interface ProjectMemoryContentBlank {\n    readonly code: 'content-blank';\n}"
          },
          {
            "name": "ProjectMemoryContentNul",
            "declaration": "export interface ProjectMemoryContentNul {\n    readonly code: 'content-nul';\n}"
          },
          {
            "name": "ProjectMemoryContentTooLong",
            "declaration": "export interface ProjectMemoryContentTooLong {\n    readonly code: 'content-too-long';\n    readonly maxChars: number;\n    readonly actualChars: number;\n}"
          },
          {
            "name": "ProjectMemoryDeleteRequest",
            "declaration": "export interface ProjectMemoryDeleteRequest extends ProjectMemoryListRequest {\n    readonly id: ProjectMemoryId;\n    readonly ifRevision: number;\n}"
          },
          {
            "name": "ProjectMemoryEntry",
            "declaration": "export interface ProjectMemoryEntry {\n    readonly id: ProjectMemoryId;\n    readonly content: string;\n    readonly createdAt: string;\n    readonly updatedAt: string;\n    readonly origin: ProjectMemoryOrigin;\n}"
          },
          {
            "name": "ProjectMemoryFailure",
            "declaration": "export type ProjectMemoryFailure = ProjectMemoryWorkspaceUnavailable | ProjectMemoryRevisionConflict | ProjectMemoryContentBlank | ProjectMemoryContentNul | ProjectMemoryContentTooLong | ProjectMemoryCapacityReached | ProjectMemoryNotFound;"
          },
          {
            "name": "ProjectMemoryId",
            "declaration": "export type ProjectMemoryId = Branded<'ProjectMemoryId'>;"
          },
          {
            "name": "ProjectMemoryListRequest",
            "declaration": "export interface ProjectMemoryListRequest {\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "ProjectMemoryNotFound",
            "declaration": "export interface ProjectMemoryNotFound {\n    readonly code: 'memory-not-found';\n    readonly id: ProjectMemoryId;\n}"
          },
          {
            "name": "ProjectMemoryOrigin",
            "declaration": "export type ProjectMemoryOrigin = 'tool' | 'command' | 'ui';"
          },
          {
            "name": "ProjectMemoryRejected",
            "declaration": "export interface ProjectMemoryRejected<E extends ProjectMemoryFailure = ProjectMemoryFailure> {\n    readonly ok: false;\n    readonly error: E;\n}"
          },
          {
            "name": "ProjectMemoryResult",
            "declaration": "export type ProjectMemoryResult<E extends ProjectMemoryFailure = ProjectMemoryFailure> = ProjectMemorySuccess<ProjectMemorySnapshot> | ProjectMemoryRejected<E>;"
          },
          {
            "name": "ProjectMemoryRevisionConflict",
            "declaration": "export interface ProjectMemoryRevisionConflict {\n    readonly code: 'revision-conflict';\n    readonly current: ProjectMemorySnapshot;\n}"
          },
          {
            "name": "ProjectMemorySnapshot",
            "declaration": "export interface ProjectMemorySnapshot {\n    readonly workspaceId: WorkspaceId;\n    readonly workspaceTitle: string;\n    readonly revision: number;\n    readonly maxEntries: number;\n    readonly maxEntryChars: number;\n    readonly entries: readonly ProjectMemoryEntry[];\n}"
          },
          {
            "name": "ProjectMemorySuccess",
            "declaration": "export interface ProjectMemorySuccess<T> {\n    readonly ok: true;\n    readonly value: T;\n}"
          },
          {
            "name": "ProjectMemoryUpdateRequest",
            "declaration": "export interface ProjectMemoryUpdateRequest extends ProjectMemoryAddRequest {\n    readonly id: ProjectMemoryId;\n}"
          },
          {
            "name": "ProjectMemoryWorkspaceUnavailable",
            "declaration": "export interface ProjectMemoryWorkspaceUnavailable {\n    readonly code: 'workspace-unavailable';\n    readonly sessionId: SessionId;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "WorkspaceId",
            "declaration": "export type WorkspaceId = Branded<'WorkspaceId'>;"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "One workspace memory mutation committed durably. Forwarded to Web clients so open memory views can refresh.",
        "summary": "One workspace memory mutation committed durably.",
        "tags": [
          {
            "name": "param",
            "argument": "payload",
            "comment": "- workspace identity and committed revision.",
            "text": "@param payload - workspace identity and committed revision.\n     *"
          },
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit"
          }
        ],
        "jsDoc": "/**\n * One workspace memory mutation committed durably. Forwarded to Web\n * clients so open memory views can refresh.\n * @param payload - workspace identity and committed revision.\n * @mode emit\n */",
        "name": "project-memory/changed",
        "mode": "emit",
        "signature": "'project-memory/changed'(payload: { workspaceId: WorkspaceId; revision: number; }): void"
      }
    ],
    "objects": []
  },
}
