/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ProjectMemoryAddRequest, ProjectMemoryDeleteRequest, ProjectMemoryListRequest, ProjectMemoryResult, ProjectMemoryUpdateRequest, ProjectMemoryWorkspaceUnavailable } from 'dsh-memory/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$70726f6a6563744d656d6f7279 {
    add: (request: ProjectMemoryAddRequest) => Promise<RemoteResult<ProjectMemoryResult>>
    delete: (request: ProjectMemoryDeleteRequest) => Promise<RemoteResult<ProjectMemoryResult>>
    list: (request: ProjectMemoryListRequest) => Promise<RemoteResult<ProjectMemoryResult<ProjectMemoryWorkspaceUnavailable>>>
    update: (request: ProjectMemoryUpdateRequest) => Promise<RemoteResult<ProjectMemoryResult>>
  }
  interface TypertRemoteMap {
    'projectMemory/add': (request: ProjectMemoryAddRequest) => Promise<RemoteResult<ProjectMemoryResult>>
    'projectMemory/delete': (request: ProjectMemoryDeleteRequest) => Promise<RemoteResult<ProjectMemoryResult>>
    'projectMemory/list': (request: ProjectMemoryListRequest) => Promise<RemoteResult<ProjectMemoryResult<ProjectMemoryWorkspaceUnavailable>>>
    'projectMemory/update': (request: ProjectMemoryUpdateRequest) => Promise<RemoteResult<ProjectMemoryResult>>
  }
  interface TypertRemoteNamespaceMap {
    'projectMemory': TypertRemoteNamespace$70726f6a6563744d656d6f7279
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
